name: Generate ASCII Artwork

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run Script
        run: sh ascii.sh
      - name: Sleep
        run: sleep 30
      - name: Upload Artifact (builder.txt)
        uses: actions/upload-artifact@v4
        with:
          name: my-build-artifact
          path: builder.txt
  second_job:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: first_job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          pip install django==4 djangorestframework

      - name: Echo
        run: echo "Deploying ................"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-build-artifact
      - name: Display structure of downloaded files

        run: ls -R
