name: A workflow for my Hello World file
on:
  schedule:
    - cron: "* * * * *"
jobs:
    build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run a shell command
        run: echo "Hello Github Action"
   build2:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Print Current Date and Time
        run: echo "Current date and time: $(date)"
      - name: Run a shell command
        run: echo "Hello Github Action"

