name: A workflow for my Hello World file
on:
  schedule:
    - cron: "* * 17 FEB * "

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run a shell command
        run: echo "Hello Github Action"
