name: Project 1
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
   workflow_dispatch:
    
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
