name: A workflow for my Hello World file
on:
  schedule:
    - cron: "* * * * *"
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo Hello Github Action
  build2:
    name: Hello world action 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo Hello Github Action
