name: Event filters and Activity types
on:
  workflow_dispatch:
  push:
    branches: [main]
#   schedule:
#     # - cron: "*/1 * * * *"
#     - cron: "*/59 * * * *"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run Command
        run: echo "This command ir ran by the ${{ github.event_name}} activity type"
