name: CI/CD Pipeline - Matrix Configuration

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  stage1:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
        DockerImages: [hello-world, alpine]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 2
    steps:
      - name: Get Docker details
        run: docker info
      - name: Get Docker Version
        run: docker version
      - name: Run Images ${matrix.DockerImages}}
        run: docker run ${{matrix.DockerImages}}
