name: Event filters and Activity types 2
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - closed
    branches:
      - main
    paths-ignore: text.txt


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run Command
        run: echo "This command is ran by the ${{ github.event_name}} activity type"
      - name: Run Command
        run: echo "This is a test command"