name: CI/CD Pipeline - Using ENV and Secrets

on:
  push:
    branches: [main]
# env:
#   CONTAINER_REGISTRY: docker.io
#   USERNAME: chiefbuilder
#   PASSWORD: Computerscience@01
#   IMAGE_NAME: flask-app
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Image
        run: echo docker build -t $CONTAINER_REGISTRY/${{secrets.DOCKER_HUB_USERNAME}}/$IMAGE_NAME:latest

      - name: Login into  Docker
        run: echo docker login --username ${{secrets.DOCKER_HUB_USERNAME}} --password ${{secrets.DOCKER_HUB_PASSWORD}}

      - name: Push to Docker
        run: echo docker push $CONTAINER_REGISTRY/${{secrets.DOCKER_HUB_USERNAME}}/$IMAGE_NAME:latest
