name: CI/CD Pipeline - Using ENV and Secrets

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    # - cron: "*/1 * * * *"
    - cron: "30 5 * * 1,3"
    - cron: "30 5 * * 2,4"

# env:
#   CONTAINER_REGISTRY: docker.io
#   USERNAME: chiefbuilder
#   PASSWORD: Computerscience@01
#   IMAGE_NAME: flask-app
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Image
        run: echo docker build -t ${{ vars.CONTAINER_REGISTRY}}/${{secrets.DOCKER_HUB_USERNAME}}/${{ vars.IMAGE_NAME}}:latest

      - name: Login into  Docker
        run: echo docker login --username ${{secrets.DOCKER_HUB_USERNAME}} --password ${{secrets.DOCKER_HUB_PASSWORD}}

      - name: Push to Docker
        run: echo docker push ${{ vars.CONTAINER_REGISTRY}}/${{secrets.DOCKER_HUB_USERNAME}}/${{ vars.IMAGE_NAME}}:latest

  test_schedule:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This step will always run"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    concurrency: 
        group: deployment
        cancel-in-progress: true
    steps:
      - name: Deploy app on instance
        run: |
          echo docker run -p 8000:8000 -d ${{ vars.CONTAINER_REGISTRY}}/${{secrets.DOCKER_HUB_USERNAME}}/${{ vars.IMAGE_NAME}}:latest
          sleep 60
