name: Workflow 1

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Multiple Commands
              run:  |
                echo "My First Github Actions Workflow"
                ls -ltra
                cat README.md
            - name: Print in ASCII Format
              run: cowsay -f dragon "Chief Builder" >> builder.txt